### PR TITLE
Automatically load imagery if any in iDeditor

### PR DESCRIPTION
**Pull request by pgiraud**
This pull request is supposed to replace https://github.com/hotosm/osm-tasking-manager/pull/178
Please @mikelmaron review.

### CODE REVIEW

**Comment by mikelmaron** [comment]
@pgiraud looks good, thanks. up for testing somewhere?

**Comment by pgiraud** [comment]
Here you are: http://tasks-dev.hotosm.org/job/368
I created a fake job using the imagery for Katmandu. License is probably wrong. This is just for test.

**Comment by mikelmaron** [comment]
worked great for me

**Comment by pierzen** [comment]
worked well for me also, but no imagery identification other then Personnalized in the Base map layer list.

For HOT, to build a better workflow passing info from the Task Manager to ID, the best would be to provide parameters for the Imagery name and Attribution, and assure that these infos are showed in ID. 

If I save the edits in ID, the info about the url of the imagery is provided in the Changeset with indication Custom.
imagery_used    Custom (http://hiu-maps.net/hot/1.0.0/kathmandu_flipped/{z}/{x}/{y}.png)
See http://www.openstreetmap.org/changeset/20400651 

Is it possible to revise the instructions from the TM this way, or would some modifications be necessary on the ID software side ?

**Comment by mikelmaron** [comment]
Modifications to iD-editor would be required, to display other parameters of the background imagery. 

My suggestion is to make that another issue, and start up discussion with iD developers. But I don't think it's a blocker for merging these pull request changes and making them live, it's certainly an improvement on the current state of things.

**Comment by pgiraud** [comment]
Thanks. Merging. And deploying on main instance as soon as possible.

**Comment by mikelmaron** [comment]
YEA!

**Pull request merged**
