### PR TITLE
add imagery link to iD

### PR DESCRIPTION
**Pull request by mikelmaron**
if imagery is set on a job, adds it to iD.

also, older tweak to allow arbitrary geometries in jobs.

### CODE REVIEW

**Comment by pgiraud** [comment]
@mikelmaron hey nice!
I have a request though. Would it be possible for you to create a new pull request with only the commits regarding the imagery links? I can quickly do it if not possible.
I prefer not to pollute the commit with code that don't have anything to do with the pull request.
We can work on the arbitrary polygon later on if you don't mind. The guys from osm.us already did successfully.

**Comment by state-hiu** [comment]
I think we need to add in a license check, so imagery_url is only set if you've agreed to the license.  You can't accept a license on a job page, so it'll always refresh.

I think it would be something like this:
% if license_accepted or not job.license:
var imagery_url = "${job.imagery}";
%else:
var imagery_url = ""
% endif

However, I don't have the tasking manager in a dev environment to test and have never used mako.

**Comment by mikelmaron** [comment]
@pgiraud sorry about that, makes sense to separate out. the easiest thing for me to do is to add another commit, removing the geometry stuff from the model, and removing those two files. let me know if that sounds ok. otherwise, if it's easy for you, that way or otherwise, fine by me if you remove the changes.

@state-hiu great catch. the last commit should address this.

@pgiraud, note i'm flying a little blind here, my python environment is not super happy after upgrading ubuntu, so will need a good test before deploy.

**Comment by mikelmaron** [comment]
covered by the other pull request

**Pull request closed without merging**
