### PR TITLE
bootstrap is in new github repo

### PR DESCRIPTION
**Pull request by mikelmaron**

### CODE REVIEW

**Comment by pgiraud** [comment]
We should probably take care of boostrap version. Shouldn't we rely on a tag / release?

**Comment by mikelmaron** [comment]
Sure, which tag? 2.x.x? How do we specify that in .gitmodules?

**Comment by pgiraud** [comment]
Once the submodule is added, you can cd to the submodule directory. Simply checkout a specified tag using the following command:
git checkout tags/<tag_name>

Then cd back to root. You should have a new change not staged for commit.

v2.3.2 should be OK for our case.

**Comment by xivk** [comment]
Possibly I'm missing something here but shouldn't the boostrap url be changed in .gitmodules? Not much experience here with working on the TM but trying to learn.

https://github.com/xivk/osm-tasking-manager/commit/55913df32299a7cd00f962326a3e4de9b0503156

**Comment by xivk** [comment]
OK I see now Mikel has done the work already! :-) sorry

**Comment by pgiraud** [comment]
Fixed with bbb902904a389b37938734175bea4f2ecdf65fae.
Sorry @mikelmaron, I wasn't able to merge your pull request since it was polluted with unrelated new commits.

**Comment by mikelmaron** [comment]
no worries, i polluted it. just glad it was noticed and fixed.

**Pull request closed without merging**
